/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArabicKeyboard: typeof import('./src/components/studio/ArabicKeyboard.vue')['default']
    BaseButton: typeof import('./resources/js/shared/components/BaseButton.vue')['default']
    BaseDialog: typeof import('./resources/js/shared/components/BaseDialog.vue')['default']
    BaseInput: typeof import('./resources/js/shared/components/BaseInput.vue')['default']
    EditorCanvas: typeof import('./src/components/studio/EditorCanvas.vue')['default']
    EditorToolbar: typeof import('./src/components/studio/EditorToolbar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    KeyButton: typeof import('./src/components/studio/KeyButton.vue')['default']
    LibraryBookCard: typeof import('./src/components/library/LibraryBookCard.vue')['default']
    LibraryEmptyCard: typeof import('./src/components/library/LibraryEmptyCard.vue')['default']
    LibraryIndex: typeof import('./src/components/library/LibraryIndex.vue')['default']
    LibraryTabs: typeof import('./src/components/library/LibraryTabs.vue')['default']
    MainFooter: typeof import('./src/components/layout/MainFooter.vue')['default']
    MainHeader: typeof import('./src/components/layout/MainHeader.vue')['default']
    MainSidebar: typeof import('./src/components/layout/MainSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudioHome: typeof import('./src/components/studio/StudioHome.vue')['default']
    StudioIndex: typeof import('./src/components/studio/StudioIndex.vue')['default']
    ThemeToggle: typeof import('./src/components/common/ThemeToggle.vue')['default']
    TiptapEditor: typeof import('./src/components/editor/TiptapEditor.vue')['default']
  }
}
