/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArabicKeyboard: typeof import('./src/components/studio/ArabicKeyboard.vue')['default']
    BaseBadge: typeof import('./resources/js/shared/components/BaseBadge.vue')['default']
    BaseBtnColorToggle: typeof import('./resources/js/shared/components/BaseBtnColorToggle.vue')['default']
    BaseBtnIconToggle: typeof import('./resources/js/shared/components/BaseBtnIconToggle.vue')['default']
    BaseBtnToggle: typeof import('./resources/js/shared/components/BaseBtnToggle.vue')['default']
    BaseButton: typeof import('./resources/js/shared/components/BaseButton.vue')['default']
    BaseCard: typeof import('./resources/js/shared/components/BaseCard.vue')['default']
    BaseChip: typeof import('./resources/js/shared/components/BaseChip.vue')['default']
    BaseCombobox: typeof import('./resources/js/shared/components/BaseCombobox.vue')['default']
    BaseComboboxOption: typeof import('./resources/js/shared/components/BaseComboboxOption.vue')['default']
    BaseContextMenu: typeof import('./resources/js/shared/components/BaseContextMenu.vue')['default']
    BaseContextMenuPanel: typeof import('./resources/js/shared/components/BaseContextMenuPanel.vue')['default']
    BaseDatePicker: typeof import('./resources/js/shared/components/BaseDatePicker.vue')['default']
    BaseDatePickerDropMenu: typeof import('./resources/js/shared/components/BaseDatePickerDropMenu.vue')['default']
    BaseDatePickerDropMenuPanel: typeof import('./resources/js/shared/components/BaseDatePickerDropMenuPanel.vue')['default']
    BaseDateTimeDropMenu: typeof import('./resources/js/shared/components/BaseDateTimeDropMenu.vue')['default']
    BaseDateTimePicker: typeof import('./resources/js/shared/components/BaseDateTimePicker.vue')['default']
    BaseDialog: typeof import('./resources/js/shared/components/dialogs/BaseDialog.vue')['default']
    BaseDrawer: typeof import('./resources/js/shared/components/BaseDrawer.vue')['default']
    BaseExpandable: typeof import('./resources/js/shared/components/BaseExpandable.vue')['default']
    BaseHoverSelect: typeof import('./resources/js/shared/components/BaseHoverSelect.vue')['default']
    BaseNestedDropMenu: typeof import('./resources/js/shared/components/BaseNestedDropMenu.vue')['default']
    BaseNestedDropMenuPanel: typeof import('./resources/js/shared/components/BaseNestedDropMenuPanel.vue')['default']
    BasePanel: typeof import('./resources/js/shared/components/BasePanel.vue')['default']
    BasePopover: typeof import('./resources/js/shared/components/BasePopover.vue')['default']
    BaseRightSidebar: typeof import('./resources/js/shared/components/BaseRightSidebar.vue')['default']
    BaseSlotSwitch: typeof import('./resources/js/shared/components/BaseSlotSwitch.vue')['default']
    BaseTab: typeof import('./resources/js/shared/components/BaseTab.vue')['default']
    BaseTabPanel: typeof import('./resources/js/shared/components/BaseTabPanel.vue')['default']
    BaseTabs: typeof import('./resources/js/shared/components/BaseTabs.vue')['default']
    BaseTabToggle: typeof import('./resources/js/shared/components/BaseTabToggle.vue')['default']
    BaseTabToggleOrDropmenu: typeof import('./resources/js/shared/components/BaseTabToggleOrDropmenu.vue')['default']
    BaseTextarea: typeof import('./resources/js/shared/components/BaseTextarea.vue')['default']
    BaseTextInput: typeof import('./resources/js/shared/components/BaseTextInput.vue')['default']
    BaseTimePicker: typeof import('./resources/js/shared/components/BaseTimePicker.vue')['default']
    BaseToggleSwitch: typeof import('./resources/js/shared/components/BaseToggleSwitch.vue')['default']
    BaseTooltip: typeof import('./resources/js/shared/components/BaseTooltip.vue')['default']
    ConfirmDialog: typeof import('./resources/js/shared/components/dialogs/ConfirmDialog.vue')['default']
    EditorCanvas: typeof import('./src/components/studio/EditorCanvas.vue')['default']
    EditorToolbar: typeof import('./src/components/editor/EditorToolbar.vue')['default']
    EmojiPicker: typeof import('./resources/js/shared/components/EmojiPicker.vue')['default']
    FloatingWrapper: typeof import('./resources/js/shared/components/FloatingWrapper.vue')['default']
    KeyButton: typeof import('./src/components/studio/KeyButton.vue')['default']
    LibraryBookCard: typeof import('./src/components/library/LibraryBookCard.vue')['default']
    LibraryBookEditor: typeof import('./src/components/library/LibraryBookEditor.vue')['default']
    LibraryBookPageId: typeof import('./src/components/library/LibraryBookPageId.vue')['default']
    LibraryCreateBookDialog: typeof import('./src/components/library/LibraryCreateBookDialog.vue')['default']
    LibraryEmptyCard: typeof import('./src/components/library/LibraryEmptyCard.vue')['default']
    LibraryIndex: typeof import('./src/components/library/LibraryIndex.vue')['default']
    LibraryTabs: typeof import('./src/components/library/LibraryTabs.vue')['default']
    MainFooter: typeof import('./src/components/layout/MainFooter.vue')['default']
    MainHeader: typeof import('./src/components/layout/MainHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudioEditor: typeof import('./src/components/studio/StudioEditor.vue')['default']
    StudioIndex: typeof import('./src/components/studio/StudioIndex.vue')['default']
    ThemeToggle: typeof import('./src/components/common/ThemeToggle.vue')['default']
    TiptapEditor: typeof import('./src/components/editor/TiptapEditor.vue')['default']
    ToastContainer: typeof import('./resources/js/shared/components/ToastContainer.vue')['default']
    ToastPopup: typeof import('./resources/js/shared/components/ToastPopup.vue')['default']
  }
}
