export const FONTS = [
  "Alexandria",
  "Alkalami",
  "Almarai",
  "Alyamama",
  "Amiri",
  "Amiri Quran",
  "Aref Ruqaa",
  "Aref Ruqaa Ink",
  "Badeen Display",
  "Baloo Bhaijaan 2",
  "Beiruti",
  "Cairo",
  "Cairo Play",
  "Cascadia Code",
  "Cascadia Mono",
  "Changa",
  "El Messiri",
  "Fustat",
  "Handjet",
  "Harmattan",
  "IBM Plex Sans Arabic",
  "Katibeh",
  "Kufam",
  "Lalezar",
  "Lateef",
  "Lemonada",
  "Mada",
  "Marhey",
  "Markazi Text",
  "Mirza",
  "Noto Kufi Arabic",
  "Noto Naskh Arabic",
  "Noto Sans Arabic",
  "Oi",
  "Parastoo",
  "Playpen Sans Arabic",
  "Qahiri",
  "Rakkas",
  "Readex Pro",
  "Reem Kufi",
  "Reem Kufi Fun",
  "Reem Kufi Ink",
  "Rubik",
  "Ruwudu",
  "Scheherazade New",
  "Tajawal",
  "Vazirmatn",
  "Vibes",
  "Zain",
];
